version: '3.1'

services:
  db:
    container_name: postgres_livraria
    image: postgres:17.2-alpine

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSAWORD: ${POSTGRES_PASSAWORD}
      POSTGRES_DB: ${POSTGRENS_DB}
      PGDATA: postgres_data

    ports: 
        - "52:5432"

    restart: always